import ExcelJS from 'exceljs'
import type { SupplierResult, SearchRequest } from '@/types'

export async function generateExcel(
  suppliers: SupplierResult[],
  searchReq: SearchRequest
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Federico Monge Consulting'
  workbook.created = new Date()

  const sheet = workbook.addWorksheet('Suppliers', {
    pageSetup: { orientation: 'landscape', fitToPage: true },
  })

  // Brand colors
  const navyFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F2D3A' } }
  const tealFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF28CFE2' } }
  const lightFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FAFE' } }

  // Search info rows
  sheet.addRow(['PROCUREMENT AGENT REPORT'])
  sheet.addRow(['Generated by Federico Monge Consulting | www.fedemongeconsulting.com'])
  sheet.addRow([])
  sheet.addRow(['Search Query:', searchReq.description])
  if (searchReq.brandOrSku) sheet.addRow(['Brand / SKU:', searchReq.brandOrSku])
  sheet.addRow(['Location:', searchReq.location])
  if (searchReq.incoterm && searchReq.incoterm !== 'Any') sheet.addRow(['Incoterm:', searchReq.incoterm])
  sheet.addRow(['Date:', new Date().toLocaleDateString('es-CO', { timeZone: 'America/Bogota' })])
  sheet.addRow([])

  // Style title
  const titleRow = sheet.getRow(1)
  titleRow.getCell(1).font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } }
  titleRow.getCell(1).fill = navyFill
  sheet.mergeCells('A1:K1')

  // Header row
  const headers = [
    'Supplier Name', 'Country', 'Address', 'Website', 'Catalog / Product Page',
    'Phone', 'Email', 'Product Details', 'Rating', 'Rating Source', 'Notes'
  ]
  const headerRow = sheet.addRow(headers)
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FF0F2D3A' } }
    cell.fill = tealFill
    cell.alignment = { vertical: 'middle', wrapText: true }
    cell.border = {
      bottom: { style: 'medium', color: { argb: 'FF0F2D3A' } },
    }
  })
  headerRow.height = 20

  // Data rows
  suppliers.forEach((s, i) => {
    const row = sheet.addRow([
      s.name,
      s.country,
      s.address,
      s.website,
      s.catalogUrl || '',
      s.phone || '',
      s.email || '',
      s.productDetails,
      s.rating || '',
      s.ratingSource || '',
      s.notes || '',
    ])
    if (i % 2 === 0) {
      row.eachCell((cell) => { cell.fill = lightFill })
    }
    row.eachCell((cell) => {
      cell.alignment = { vertical: 'top', wrapText: true }
    })
    row.height = 40
  })

  // Column widths
  sheet.columns = [
    { key: 'A', width: 25 },
    { key: 'B', width: 15 },
    { key: 'C', width: 30 },
    { key: 'D', width: 30 },
    { key: 'E', width: 30 },
    { key: 'F', width: 18 },
    { key: 'G', width: 28 },
    { key: 'H', width: 40 },
    { key: 'I', width: 12 },
    { key: 'J', width: 18 },
    { key: 'K', width: 25 },
  ]

  sheet.getRow(sheet.rowCount + 2).getCell(1).value =
    'Generated by Procurement Agent | fedemongeconsulting.com'

  const buf = await workbook.xlsx.writeBuffer()
  return Buffer.from(buf)
}
